import http from 'node:http';
import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import { fileURLToPath } from 'node:url';

const root = path.dirname(fileURLToPath(import.meta.url));
const dataDir = path.join(root, 'data');
const dataFile = path.join(dataDir, 'store.json');
fs.mkdirSync(dataDir, { recursive: true });
const seed = { profile: { name: 'Jordan Davis', title: 'Product Designer', email: '', location: 'New York, NY', skills: ['Product strategy', 'UX research', 'Design systems'] }, jobs: [{ id: 1, company: 'Airbnb', initial: 'A', title: 'Senior Product Designer', place: 'Remote · United States', salary: '$145k – $182k', match: '96%', status: 'review' }, { id: 2, company: 'Notion', initial: 'N', title: 'Product Designer, Growth', place: 'New York, NY · Hybrid', salary: '$130k – $165k', match: '92%', status: 'review' }, { id: 3, company: 'Linear', initial: 'L', title: 'Product Designer, Core', place: 'Remote · North America', salary: '$140k – $175k', match: '89%', status: 'review' }], applications: [], runs: [], integrations: [{ id: 'greenhouse', name: 'Greenhouse', status: 'available' }, { id: 'lever', name: 'Lever', status: 'available' }, { id: 'linkedin', name: 'LinkedIn', status: 'available' }, { id: 'indeed', name: 'Indeed', status: 'available' }] };
const read = () => { if (!fs.existsSync(dataFile)) fs.writeFileSync(dataFile, JSON.stringify(seed, null, 2)); return JSON.parse(fs.readFileSync(dataFile)); };
const save = data => fs.writeFileSync(dataFile, JSON.stringify(data, null, 2));
const send = (res, status, body) => { res.writeHead(status, { 'content-type': 'application/json' }); res.end(JSON.stringify(body)); };
const parse = req => new Promise(resolve => { let text = ''; req.on('data', chunk => text += chunk); req.on('end', () => resolve(text ? JSON.parse(text) : {})); });
function templateResume(profile, job) { return `${profile.name}\n${profile.title}\n${profile.location} · ${profile.email}\n\nTARGET ROLE\n${job.title} at ${job.company}\n\nSUMMARY\n${profile.title} with experience aligned to ${job.title}. Prepared for a focused application to ${job.company}.\n\nCORE SKILLS\n${(profile.skills || []).join(' • ')}\n\nAPPLICATION NOTES\nTailored draft generated from the saved Northstar profile. Review before submitting.`; }
async function generateResume(profile, job) { const prompt = `Create a concise, truthful resume draft. Do not invent facts. Use sections SUMMARY, CORE SKILLS, EXPERIENCE GUIDANCE, APPLICATION NOTES. Candidate: ${JSON.stringify(profile)}. Job: ${JSON.stringify(job)}.`; if (process.env.OPENAI_API_KEY) { const response = await fetch('https://api.openai.com/v1/responses', { method: 'POST', headers: { 'content-type': 'application/json', authorization: `Bearer ${process.env.OPENAI_API_KEY}` }, body: JSON.stringify({ model: process.env.OPENAI_MODEL || 'gpt-5-mini', input: prompt, store: false }) }); if (response.ok) { const result = await response.json(); return { text: result.output_text || templateResume(profile, job), provider: 'openai' }; } } if (process.env.GEMINI_API_KEY) { const model = process.env.GEMINI_MODEL || 'gemini-2.5-flash'; const response = await fetch(`https://generativelanguage.googleapis.com/v1beta/models/${model}:generateContent?key=${process.env.GEMINI_API_KEY}`, { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ contents: [{ parts: [{ text: prompt }] }] }) }); if (response.ok) { const result = await response.json(); return { text: result.candidates?.[0]?.content?.parts?.[0]?.text || templateResume(profile, job), provider: 'gemini' }; } } return { text: templateResume(profile, job), provider: 'template' }; }
async function discover(data) { if (!process.env.JOB_FEED_URL) return data.jobs.filter(job => job.status === 'review').length; const response = await fetch(process.env.JOB_FEED_URL); if (!response.ok) throw new Error(`Job feed returned ${response.status}`); const incoming = await response.json(); const jobs = Array.isArray(incoming) ? incoming : incoming.jobs; for (const item of jobs || []) { if (!item.title || !item.company) continue; if (data.jobs.some(job => job.title === item.title && job.company === item.company)) continue; data.jobs.unshift({ id: Date.now() + Math.floor(Math.random() * 1000), company: item.company, initial: item.company[0].toUpperCase(), title: item.title, place: item.place || item.location || 'Location not listed', salary: item.salary || 'Salary not listed', match: item.match || '—', source: item.source || 'Configured feed', status: 'review', url: item.url || '' }); } return data.jobs.filter(job => job.status === 'review').length; }
async function api(req, res, url) { const data = read(); const parts = url.pathname.split('/').filter(Boolean); if (url.pathname === '/api/health') return send(res, 200, { ok: true }); if (url.pathname === '/api/state') return send(res, 200, data); if (url.pathname === '/api/profile' && req.method === 'GET') return send(res, 200, data.profile); if (url.pathname === '/api/profile' && req.method === 'PUT') { data.profile = { ...data.profile, ...await parse(req) }; save(data); return send(res, 200, data.profile); } if (url.pathname === '/api/jobs') return send(res, 200, data.jobs); if (parts[1] === 'jobs' && parts[3] === 'approve') { const job = data.jobs.find(item => String(item.id) === parts[2]); if (!job) return send(res, 404, { error: 'Job not found' }); job.status = 'approved'; const application = { id: crypto.randomUUID(), jobId: job.id, company: job.company, title: job.title, status: 'resume_draft', createdAt: new Date().toISOString() }; job.applicationId = application.id; data.applications.push(application); save(data); return send(res, 200, job); } if (parts[1] === 'jobs' && parts[3] === 'dismiss') { const job = data.jobs.find(item => String(item.id) === parts[2]); if (!job) return send(res, 404, { error: 'Job not found' }); job.status = 'dismissed'; save(data); return send(res, 200, job); } if (url.pathname === '/api/applications') return send(res, 200, data.applications); if (parts[1] === 'applications' && parts[3] === 'tailor' && req.method === 'POST') { const application = data.applications.find(item => item.id === parts[2]); if (!application) return send(res, 404, { error: 'Application not found' }); const job = data.jobs.find(item => item.id === application.jobId) || application; const result = await generateResume(data.profile, job); application.status = 'resume_ready'; application.resume = { version: `${application.company} — tailored resume`, generatedAt: new Date().toISOString(), ...result }; save(data); return send(res, 200, application); } if (url.pathname === '/api/integrations' && req.method === 'GET') return send(res, 200, data.integrations); if (parts[1] === 'integrations' && parts[3] === 'connect' && req.method === 'POST') { const integration = data.integrations.find(item => item.id === parts[2]); if (!integration) return send(res, 404, { error: 'Integration not found' }); integration.status = 'needs_login'; integration.connectedAt = new Date().toISOString(); save(data); return send(res, 200, integration); } if (url.pathname === '/api/runs' && req.method === 'GET') return send(res, 200, data.runs); if (url.pathname === '/api/runs' && req.method === 'POST') { const found = await discover(data); const run = { id: crypto.randomUUID(), status: 'completed', found, startedAt: new Date().toISOString() }; data.runs.unshift(run); save(data); return send(res, 201, run); } return send(res, 404, { error: 'Not found' }); }
async function scheduledRun() { const data = read(); const now = new Date(); const hour = now.getHours(); if (hour !== 8 && hour !== 18) return; const key = `${now.toISOString().slice(0, 10)}-${hour}`; if (data.runs.some(run => run.scheduleKey === key)) return; const found = await discover(data); data.runs.unshift({ id: crypto.randomUUID(), status: 'completed', trigger: 'schedule', scheduleKey: key, found, startedAt: now.toISOString() }); save(data); }
setInterval(scheduledRun, 60000); scheduledRun();
const mime = { '.html': 'text/html', '.js': 'text/javascript', '.css': 'text/css' };
http.createServer((req, res) => { const url = new URL(req.url, 'http://localhost'); if (url.pathname.startsWith('/api/')) return api(req, res, url); const file = path.join(root, url.pathname === '/' ? 'index.html' : url.pathname); if (!fs.existsSync(file)) return send(res, 404, { error: 'Not found' }); res.writeHead(200, { 'content-type': mime[path.extname(file)] || 'application/octet-stream' }); fs.createReadStream(file).pipe(res); }).listen(process.env.PORT || 3000, () => console.log(`Northstar running on http://localhost:${process.env.PORT || 3000}`));
